"""
Paper-style figures for anomaly evaluation.

This module defines a set of functions to produce publication-quality
plots that mirror those generated by the original MATLAB Assaying Anomalies
toolkit. Each function operates on the outputs of the Python
evaluation pipeline (i.e. the dictionary returned by
``aa.analysis.anomaly_pipeline.evaluate_signals``) or on the metrics
dictionary. The figures are constructed using ``matplotlib`` and
return ``matplotlib.figure.Figure`` objects for further customisation.

No new analytical methods are introduced; the plots simply visualise
existing results. By default the functions use the ``Agg`` backend so
they may be called in headless environments (e.g. unit tests).
"""

from __future__ import annotations

from typing import Any, Dict, Optional, cast

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.figure import Figure

from aa.analysis.anomaly_metrics import mean_return

__all__ = [
    "plot_cumulative_returns",
    "plot_performance_comparison",
    "plot_return_distribution",
    "plot_portfolio_spreads",
]


def _prepare_cumulative(series: pd.Series) -> pd.Series:
    """Compute the cumulative return series from a periodic return series."""
    ser = pd.to_numeric(series, errors="coerce").dropna()
    cumulative = (1.0 + ser).cumprod() - 1.0
    return cumulative


def plot_cumulative_returns(
    results: Dict[str, Dict[str, Any]],
    *,
    value_weighted: bool = False,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> Figure:
    """Plot cumulative high-minus-low returns for each anomaly."""
    col = "hl_vw" if value_weighted else "hl_ew"
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = cast(Figure, ax.figure)

    for name, out in results.items():
        hl_ts = out.get("hl_ts")
        if hl_ts is None or col not in hl_ts.columns:
            continue
        cum = _prepare_cumulative(hl_ts[col])
        if cum.empty:
            continue
        ax.plot(cum.index, cum.values, label=name)

    ax.axhline(0.0, color="black", linewidth=0.8, linestyle="--")
    ax.set_xlabel("Date")
    ax.set_ylabel("Cumulative return")
    if title is None:
        title = "Cumulative high-low returns" + (" (VW)" if value_weighted else " (EW)")
    ax.set_title(title)
    ax.legend(loc="best", fontsize="small")
    fig.tight_layout()
    return fig


def plot_performance_comparison(
    metrics: Dict[str, Dict[str, Any]],
    *,
    metric: str = "mean_ew",
    top_n: Optional[int] = None,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> Figure:
    """Create a bar chart comparing anomalies by a chosen metric."""
    vals = {name: stats.get(metric, float("nan")) for name, stats in metrics.items()}
    ser = pd.Series(vals).dropna().sort_values(ascending=False)

    if top_n is not None:
        ser = ser.iloc[:top_n]

    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = cast(Figure, ax.figure)

    ser.plot(kind="bar", ax=ax, color="tab:blue")
    ax.set_ylabel(metric)
    ax.set_xlabel("Anomaly")
    if title is None:
        title = f"Anomaly comparison by {metric}"
    ax.set_title(title)
    fig.tight_layout()
    return fig


def plot_return_distribution(
    results: Dict[str, Dict[str, Any]],
    *,
    value_weighted: bool = False,
    bins: int = 30,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> Figure:
    """Plot histograms of high-minus-low returns for each anomaly."""
    col = "hl_vw" if value_weighted else "hl_ew"
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = cast(Figure, ax.figure)

    for name, out in results.items():
        hl_ts = out.get("hl_ts")
        if hl_ts is None or col not in hl_ts.columns:
            continue
        data = pd.to_numeric(hl_ts[col], errors="coerce").dropna()
        if data.empty:
            continue
        ax.hist(
            data.values,
            bins=bins,
            alpha=0.5,
            label=name,
            edgecolor="black",
            linewidth=0.3,
        )

    ax.set_xlabel("Return")
    ax.set_ylabel("Frequency")
    if title is None:
        title = "Distribution of high-low returns" + (
            " (VW)" if value_weighted else " (EW)"
        )
    ax.set_title(title)
    ax.legend(loc="best", fontsize="small")
    fig.tight_layout()
    return fig


def plot_portfolio_spreads(
    results: Dict[str, Dict[str, Any]],
    *,
    value_weighted: bool = False,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> Figure:
    """Plot average high-minus-low portfolio spreads across anomalies."""
    col = "hl_vw" if value_weighted else "hl_ew"
    means: Dict[str, float] = {}

    for name, out in results.items():
        hl_ts = out.get("hl_ts")
        if hl_ts is None or col not in hl_ts.columns:
            continue
        series = pd.to_numeric(hl_ts[col], errors="coerce").dropna()
        if series.empty:
            continue
        means[name] = mean_return(series)

    if not means:
        if ax is None:
            fig, ax = plt.subplots(figsize=(8, 4))
        else:
            fig = cast(Figure, ax.figure)
        ax.set_title("No portfolio spread data")
        return fig

    ser = pd.Series(means).sort_values(ascending=False)

    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = cast(Figure, ax.figure)

    ser.plot(kind="bar", ax=ax, color="tab:green")
    ax.set_ylabel("Mean return")
    ax.set_xlabel("Anomaly")
    if title is None:
        title = "Average high-low spreads" + (" (VW)" if value_weighted else " (EW)")
    ax.set_title(title)
    fig.tight_layout()
    return fig
