"""
Paper‑style figures for anomaly evaluation.

This module defines a set of functions to produce publication‑quality
plots that mirror those generated by the original MATLAB Assaying Anomalies
toolkit.  Each function operates on the outputs of the Python
evaluation pipeline (i.e. the dictionary returned by
``aa.analysis.anomaly_pipeline.evaluate_signals``) or on the metrics
dictionary.  The figures are constructed using ``matplotlib`` and
return either a ``matplotlib.figure.Figure`` or an ``Axes`` object for
further customisation.

No new analytical methods are introduced – the plots simply visualise
existing results.  By default the functions use the ``Agg`` backend so
they may be called in headless environments (e.g. unit tests).
"""

from __future__ import annotations

from typing import Dict, Any, Optional

import matplotlib

matplotlib.use("Agg")  # Use a non‑interactive backend suitable for testing
import matplotlib.pyplot as plt
import pandas as pd

from aa.analysis.anomaly_metrics import mean_return

__all__ = [
    "plot_cumulative_returns",
    "plot_performance_comparison",
    "plot_return_distribution",
    "plot_portfolio_spreads",
]


def _prepare_cumulative(series: pd.Series) -> pd.Series:
    """Compute the cumulative return series from a periodic return series.

    Returns (1 + r).cumprod() - 1 so that 0 corresponds to the starting
    wealth of 1.  Missing values are ignored.
    """
    ser = pd.to_numeric(series, errors="coerce").dropna()
    cumulative = (1.0 + ser).cumprod() - 1.0
    return cumulative


def plot_cumulative_returns(
    results: Dict[str, Dict[str, Any]],
    *,
    value_weighted: bool = False,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> plt.Figure:
    """Plot cumulative high‑minus‑low returns for each anomaly.

    For each anomaly in ``results``, this function extracts the
    high‑minus‑low return series from the ``'hl_ts'`` DataFrame, computes
    its cumulative sum and plots it as a time series.  The resulting
    figure resembles the cumulative return plots in the original MATLAB
    toolkit.  All series are plotted on the same axes for easy
    comparison.

    Parameters
    ----------
    results : dict
        Output from :func:`aa.analysis.anomaly_pipeline.evaluate_signals`.
    value_weighted : bool, default False
        Plot value‑weighted spreads if True; otherwise plot
        equal‑weighted spreads.
    ax : matplotlib.axes.Axes, optional
        Axes on which to draw the plot.  If None, a new figure and axes
        are created.
    title : str, optional
        Title for the plot.  If None, a default title is used.

    Returns
    -------
    Figure
        The ``matplotlib`` figure containing the cumulative return plot.
    """
    col = "hl_vw" if value_weighted else "hl_ew"
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = ax.figure
    for name, out in results.items():
        hl_ts = out.get("hl_ts")
        if hl_ts is None or col not in hl_ts.columns:
            continue
        cum = _prepare_cumulative(hl_ts[col])
        if cum.empty:
            continue
        ax.plot(cum.index, cum.values, label=name)
    ax.axhline(0.0, color="black", linewidth=0.8, linestyle="--")
    ax.set_xlabel("Date")
    ax.set_ylabel("Cumulative return")
    if title is None:
        title = "Cumulative high–low returns" + (" (VW)" if value_weighted else " (EW)")
    ax.set_title(title)
    ax.legend(loc="best", fontsize="small")
    fig.tight_layout()
    return fig


def plot_performance_comparison(
    metrics: Dict[str, Dict[str, Any]],
    *,
    metric: str = "mean_ew",
    top_n: Optional[int] = None,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> plt.Figure:
    """Create a bar chart comparing anomalies by a chosen metric.

    Parameters
    ----------
    metrics : dict
        Dictionary of performance metrics keyed by anomaly name.
    metric : str, default ``"mean_ew"``
        Which metric to plot.  Must be present in each entry of
        ``metrics``.
    top_n : int, optional
        If provided, only the top ``n`` anomalies according to the
        selected metric are shown.  Ranking assumes larger values are
        better.
    ax : matplotlib.axes.Axes, optional
        Axes on which to draw the plot.  If None, a new figure and axes
        are created.
    title : str, optional
        Plot title.  If None, a default title is constructed.

    Returns
    -------
    Figure
        The figure containing the bar chart.
    """
    # Extract the metric values into a Series
    vals = {name: stats.get(metric, float("nan")) for name, stats in metrics.items()}
    ser = pd.Series(vals).dropna()
    # Sort descending by default (best performers first)
    ser = ser.sort_values(ascending=False)
    if top_n is not None:
        ser = ser.iloc[:top_n]
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = ax.figure
    ser.plot(kind="bar", ax=ax, color="tab:blue")
    ax.set_ylabel(metric)
    ax.set_xlabel("Anomaly")
    if title is None:
        title = f"Anomaly comparison by {metric}"
    ax.set_title(title)
    fig.tight_layout()
    return fig


def plot_return_distribution(
    results: Dict[str, Dict[str, Any]],
    *,
    value_weighted: bool = False,
    bins: int = 30,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> plt.Figure:
    """Plot histograms of high‑minus‑low returns for each anomaly.

    Each anomaly's high‑minus‑low return series is plotted as a separate
    histogram on the same axes with semi‑transparent bars.  This makes
    it easy to see the distribution of returns across anomalies.  If no
    axes are supplied, a new figure and axes are created.

    Parameters
    ----------
    results : dict
        Output of :func:`aa.analysis.anomaly_pipeline.evaluate_signals`.
    value_weighted : bool, default False
        Use value‑weighted spreads (``hl_vw``) if True; otherwise use
        equal‑weighted spreads (``hl_ew``).
    bins : int, default 30
        Number of histogram bins.
    ax : matplotlib.axes.Axes, optional
        Axes on which to draw the histograms.
    title : str, optional
        Title for the plot.

    Returns
    -------
    Figure
        The figure containing the return distribution histograms.
    """
    col = "hl_vw" if value_weighted else "hl_ew"
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = ax.figure
    for name, out in results.items():
        hl_ts = out.get("hl_ts")
        if hl_ts is None or col not in hl_ts.columns:
            continue
        data = pd.to_numeric(hl_ts[col], errors="coerce").dropna()
        if data.empty:
            continue
        ax.hist(
            data.values,
            bins=bins,
            alpha=0.5,
            label=name,
            edgecolor="black",
            linewidth=0.3,
        )
    ax.set_xlabel("Return")
    ax.set_ylabel("Frequency")
    if title is None:
        title = "Distribution of high–low returns" + (
            " (VW)" if value_weighted else " (EW)"
        )
    ax.set_title(title)
    ax.legend(loc="best", fontsize="small")
    fig.tight_layout()
    return fig


def plot_portfolio_spreads(
    results: Dict[str, Dict[str, Any]],
    *,
    value_weighted: bool = False,
    ax: Optional[plt.Axes] = None,
    title: Optional[str] = None,
) -> plt.Figure:
    """Plot average high–low portfolio spreads across anomalies.

    This function computes the mean of the high‑minus‑low spreads for
    each anomaly (equal‑ or value‑weighted) and presents them as a
    bar chart.  The resulting figure corresponds to the portfolio
    spread plots found in the MATLAB toolkit.  Only anomalies with
    available high‑low series are included.

    Parameters
    ----------
    results : dict
        Output from :func:`aa.analysis.anomaly_pipeline.evaluate_signals`.
    value_weighted : bool, default False
        Use value‑weighted spreads (``hl_vw``) if True; otherwise use
        equal‑weighted spreads (``hl_ew``).
    ax : matplotlib.axes.Axes, optional
        Axes on which to draw the plot.  If None, a new figure is
        created.
    title : str, optional
        Title for the figure.

    Returns
    -------
    Figure
        The figure containing the portfolio spread bar chart.
    """
    col = "hl_vw" if value_weighted else "hl_ew"
    means = {}
    for name, out in results.items():
        hl_ts = out.get("hl_ts")
        if hl_ts is None or col not in hl_ts.columns:
            continue
        series = pd.to_numeric(hl_ts[col], errors="coerce").dropna()
        if series.empty:
            continue
        means[name] = mean_return(series)
    if not means:
        # Create an empty plot if no data
        if ax is None:
            fig, ax = plt.subplots(figsize=(8, 4))
        else:
            fig = ax.figure
        ax.set_title("No portfolio spread data")
        return fig
    ser = pd.Series(means).sort_values(ascending=False)
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 4))
    else:
        fig = ax.figure
    ser.plot(kind="bar", ax=ax, color="tab:green")
    ax.set_ylabel("Mean return")
    ax.set_xlabel("Anomaly")
    if title is None:
        title = "Average high–low spreads" + (" (VW)" if value_weighted else " (EW)")
    ax.set_title(title)
    fig.tight_layout()
    return fig
